# frozen_string_literal: true

source "https://rubygems.org"

# REST API framework
gem "grape", "~> 1.0"

# gem "hanami-model", "~> 1.0"
# gem "pg"

group :development do
  gem "shotgun", "~> 0.9.2"
end

group :test, :development do
  gem "rubocop", "~> 0.49"
end

group :test do
  gem "minitest", "~> 5.10.3"
end

group :production do
  # gem 'puma'
end
