FORMAT: 1A
HOST: http://fixme/

# Photobank Backend

## Application Status [/status]

### Get application status [GET]

Get information on and the current status of the application instance.
Returns 200 if the application is healthy and ready to do work.

This endpoint can be used by the load balancer to determine instance health.

+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)

    A successful response indicating that the application instance is healthy.

    + Attributes (object)

        + `status` (string) - Current application status

    + Body

            {
                "data": {
                    "status": "ok"
                }
            }


## Feed [/v1/feed]

A Feed is the singleton resource that represents a user's feed. It contains a
number of posts.

### Get current feed [GET]

Get the user's feed.

+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)

    A successful response with feed content.

    + Attributes (object)

        + `data` (object, required) - Indication that the export is queued for processing later.
            + `items` (array[Post], required) - Items in the user's feed
    + Body

            {
                "data": {
                    "items": [
                        {
                            "type": "post",
                            "text": "Hello, Sailor!",
                            "image": "https://cdn.example.com/my-cool-pic.gif"
                        },
                        {
                            "type": "post",
                            "text": "No image here!"
                        }
                    ]
                }
            }


# Data structures

## Post (object)

Posts are the resource that fills the user's feed. They are items of content
with optional text and image that are posted by other users.

+ `type` (string, required) - Always the string "post".
+ `text` (string, required) - The textual content of the post.
+ `image` (string) - An optional link to an image associated with the post.
